version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: confirm files
          command: ls

      - run:
          name: make virtualenv and install some deps
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip ipython jupyter

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: run virtualenv and install commandline
          command: |
            . venv/bin/activate
            python setup.py install
            asekuro

      - run:
         name: check help outputs of commandline and run pytests
         command: |
            . venv/bin/activate
            pytest --verbose
            asekuro test tests/good-nb.ipynb
            asekuro test tests/data-nb.ipynb

      - store_artifacts:
          path: test-reports
          destination: test-reports
