version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: confirm files
          command: ls

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: make virtualenv and install some deps
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -e .

      - run:
          name: run virtualenv and install commandline + run it
          command: |
            . venv/bin/activate
            python setup.py install
            asekuro --help

      - run:
         name: check help outputs of commandline and run pytests
         command: |
            . venv/bin/activate
            pytest --verbose tests/test_commandline.py

      - run:
         name: test within a docker container for good measure
         command: |
            . venv/bin/activate
            pytest --verbose tests/test_docker.py

      - store_artifacts:
          path: test-reports
          destination: test-reports
